vpasis/app/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the Closure to execute when that URI is requested.
  |
 */

class PremissionCheck {

    private $access = '0';
    private $rangeadmin = 900000;
    private $grp = '';
    protected $lastStudentRegistred;

    public function __construct() {
        if (Session::get('uid') >= $this->rangeadmin) {
            $tokendb = Admin::where('uid', '=', Session::get('uid'))->get()->count();
            if ($tokendb) {
                $this->access = 2;
            } else {
                $this->access = 1;
            }

            //  $this->lastStudentRegistred = Studenti::lastStudent();
            //  View::share('lastStudentRegistred',$this->lastStudentRegistred);
        } else {
            $tokendb = Studenti::where('uid', '=', Session::get('uid'))->get()->count();
            if ($tokendb) {
                $this->access = 2;
            } else {
                $this->access = 1;
            }
        }
    }

    public function isLogin() {
        return $this->access;
    }

}

Route::get('/pr', 'PrintController@index');
$check = new PremissionCheck();


/* ____________________________________________________________________________________________________________________________________________________________
 */
// Language Pack
if (!Session::get('lang')) {
    Session::put('lang', 'sq');
}
App::setLocale(Session::get('lang'));


// Authentication
if ($check->isLogin() == 2) {
    if (Session::get('uid') >= 900000) {
        $user = Admin::where('uid', '=', Session::get('uid'))->select('grp')->get();
// Split accesss
        if ($user[0]['grp'] == Enum::admin) {


            Route::controller('/smps/admin/website', 'AdminwebsiteController');
            Route::controller('/smps/admin/options', 'OptionsController');
            Route::controller('/smps/admin/staff', 'StaffController');
            Route::controller('/smps/admin/student', 'StudentController');
            Route::controller('/smps/admin/vijushmeria', 'VijushmeriaController');
            Route::controller('/smps/admin/fee','FeeController');
            Route::controller('/smps/admin/provimet','ProvimetController');


            Route::put('/smps/admin/setting', 'SettingsController@Update');
            Route::get('/smps/admin/setting', 'SettingsController@Index');

            Route::controller('/smps/admin/misc', 'AdminMiscController');
            //Route::get('/smps/admin/slist', 'AdminController@getSlist');
            //Route::get('/smps/admin/print-slist/{id}/{ids}', 'AdminController@getPrintSlist');
            Route::get('/smps/admin/slist', 'admin\DashboardController@Dashboard');
            Route::post('/smps/admin/sortaca', 'AdminController@postSortaca');
            Route::get('/smps/admin/hsub/print/{id}', 'OrariController@PrintOrari');
            Route::resource('/smps/admin/hsub', 'OrariController'); // Konfigurimi Orarit
            Route::controller('/smps/admin/', 'AdminController');
            Route::controller('/smps/admin/ajax', 'AjaxController');
            Route::controller('/smps/admin/departments', 'DepartmentsController');
            Route::get('/smps/admin/person/{id}/print', 'PersonController@print_transkript');
            Route::get('/smps/admin/person/{id}/pagesa/print', 'PersonController@PrintPagesa');
            Route::post('/smps/admin/person/{id}/pagesa', 'PersonController@storepagesa');
            Route::get('/smps/admin/person/print-kontrata/', 'PersonController@getPrintKontrata');
            Route::resource('/smps/admin/person', 'PersonController');
            Route::controller('/smps/admin/warn', 'WarnController');
            Route::controller('/smps/admin/search', 'SearchPersonController');
            Route::controller('/smps/admin/rnotat', 'NotimetController');
            Route::controller('/smps/admin/news', 'NewsController');
            Route::controller('/smps/admin/prof', 'ProfController');
            Route::controller('/smps/admin/assign', 'AssignController');
            Route::controller('/smps/admin/inbox', 'MsgController');
            Route::controller('/smps/admin/rating', 'RatingController');
            Route::get('/smps/admin/ratingprintprof/', 'RatingController@Printprof');
            //redirect
            Route::get('/smps/', function() {
                return Redirect::to('/smps/admin');
            });
        } else if ($user[0]['grp'] == Enum::prof) {
            Route::controller('/smps/prof', 'ProfessorController');
            Route::controller('/smps/admin/ajax', 'AjaxController');
            Route::post('/smps/prof/search', 'SearchPersonController@postIndex');
        }
    } else {
        Route::get('/smps/', function() {
            return Redirect::to('/smps/student');
        });
        Route::controller('/smps/admin/ajax', 'AjaxController');
    }
} else if ($check->isLogin() != 2) {
    Route::controller('/smps/', 'AuthController');
}
Route::get('/smps/logout', 'AuthController@getLogout');
/*
  // developer Mode Admin
  Route::get('/dev', function() {
  return View::make('website.post', ['title' => 'titulli']);
  });
  Route::get('/dev/post', function() {
  return View::make('website.postread', ['title' => 'titulli']);
  });
  Route::get('/dev/team', function() {
  return View::make('website.team', ['title' => 'titulli']);
  });
 * */
Route::controller('/', 'WebsiteController');

vpasis/app/controllers/Enum.php
<?php

class Enum extends Controller {
    /*
     * ________________________________ | Autori: Alban Mulaki | | E-Mail: alban.mulaki@gmail.com | ________________________________
     */
    /*
     * Grupet per access
     */

    const student = 1;
    const puntor = 2;
    const prof = 3;
    const referent = 4;
    const dekani = 5;
    const drejtori = 6;
    const admin = 7;
    const asistent = 8;
    const normal = 0;
    const high = 1;
    const critical = 2;
    const seen = 1;
    const noseen = 0;
    const thread = 1;
    const nothread = 2;
    const locked = 1;
    const nolocked = 0;
    const closed = 0;
    /*
     * Statusi studenteve
     */
    const irregullt = 0;
    const joirregullt = 1;
    /*
     * Pagesat
     */
    const kontrat = 0;
    const jokontrat = 1;
    /*
     * Provimet
     */
    const notalbum = 0;
    const album = 1;
    const paraqitur = 1;
    const paraqiturprezent = 2;
    const refuzuar = 1;
    const parefuzuar = 0;
    const notdeleted = 0;
    const deleted = 1;

    /*
     * gradata shkencore
     */
    const master = 4;
    const phd = 1;
    const dr = 2;
    const akademik = 3;
    const phdcan = 5;

    public static function convertrefuzimin($ref) {
        if ($ref == self::parefuzuar) {
            return Lang::get('general.yes');
        } else if ($ref == self::refuzuar) {
            return Lang::get('general.no');
        }
    }

    /*
     * Gjinia
     */

    const mashkull = 0;
    const femer = 1;
    const no = 0;
    const yes = 1;
    const pending = 2;
    const hene = 0;
    const marte = 1;
    const merkure = 2;
    const enjete = 3;
    const premte = 4;
    const shtune = 5;
    const diel = 6;
    const grupiA = 0;
    const grupiB = 1;
    const grupiC = 2;
    const transfer = 1;
    const jotransfer = 0;
    const bachelor = 1;
    const absolvent = 4;
    const active = 1;
    const passive = 2;
    const zgjedhore = 1;
    const jozgjedhore = 0;
    const notlocksem = 0;
    const locksem = 1;
    const confirmed = 1;
    const notconfirmed = 0;


    # Check Responses
    const successful = 1;
    const failed = 2;

    /*
     * gjendjet e afati te provimeve
     */
    const mbyllur = 1;
    const hapur = 2;
    const perpunim = 3;

    public static function getGjendjetProvimeve() {
        return array(
            self::mbyllur => Lang::get('general.closed'),
            self::perpunim => Lang::get('general.prepare'),
            self::hapur => Lang::get('general.public')
        );
    }

    /*
     * Llojet e pagesave
     */

    const pagessemestri = 1;
    const pagestjeter = 2;

    public static function getLlojetPagesave() {
        return array(-1 => Lang::get('general.select_feetype'),
            self::pagessemestri => Lang::get('general.fee_semester'),
            self::pagestjeter => Lang::get('general.other')
        );
    }

    public static function convertLlojetPagesave($acc) {

        switch ($acc) {
            case self::pagessemestri :
                return Lang::get('general.fee_semester');
                break;
            case self::pagestjeter :
                return Lang::get('general.other');
                break;
        }
    }

    public static function getGjinia() {
        return array(-1 => Lang::get('general.gender'),
            self::mashkull => Lang::get('general.male'),
            self::femer => Lang::get('general.female')
        );
    }

    public static function convertGjinia($acc) {
        switch ($acc) {
            case self::mashkull :
                return Lang::get('general.male');
                break;
            case self::femer :
                return Lang::get('general.female');
                break;
        }
    }

    public static function convertDetyra($acc) {
        switch ($acc) {
            case self::prof :
                return Lang::get('general.lecturer');
                break;
            case self::asistent :
                return Lang::get('general.assistent');
                break;
        }
    }

    /*
     * Return array for combobox
     */

    public static function getActive() {
        return array(Enum::active => Lang::get('general.active'),
            Enum::passive => Lang::get('general.passive'));
    }

    /*
     * Return array for combobox
     */

    public static function getZgjedhore() {
        return array(Enum::zgjedhore => Lang::get('general.yes'),
            Enum::jozgjedhore => Lang::get('general.no'));
    }

    /*
     * Return array for combobox
     */

    public static function getGrp() {
        return array(-1 => Lang::get('general.position_office_choose'),
            self::prof => Lang::get('general.lecturer'),
            self::asistent => Lang::get('general.assistent'),
            self::referent => Lang::get('general.referent_e'),
            self::asistent => Lang::get('general.assistent'),
            self::admin => Lang::get('general.admin')
        );
    }

    const v2011 = "2011-2012";
    const v2012 = "2012-2013";
    const v2013 = "2013-2014";
    const v2014 = "2014-2015";
    const v2015 = "2015-2016";

    public static function getVitiAka() {
        return array(-1 => Lang::get('general.choose_academic_year'),
            self::v2011 => self::v2011,
            self::v2012 => self::v2012,
            self::v2013 => self::v2013,
            self::v2014 => self::v2014,
            self::v2015 => self::v2015,
        );
    }

    /*
     * Return array for combobox
     */

    public static function getStatus() {
        return array(self::irregullt => Lang::get('general.regular'),
            self::joirregullt => Lang::get('general.not_regular')
        );
    }

    /*
     * Return array for combobox
     */

    public static function getLevel() {
        return array(self::bachelor => Lang::get('general.bachelor'),
            self::master => Lang::get('general.master')
        );
    }

    /*
     * Return array for combobox
     */

    public static function getGrade() {
        return array(
            self::master => Lang::get('general.msc'),
            self::phdcan => Lang::get('general.phdcandidat'),
            self::phd => Lang::get('general.phd'),
            self::dr => Lang::get('general.dr'),
            self::akademik => Lang::get('general.academic'));
    }

    /*
     * Return array for combobox
     */

    public static function getSemester() {
        return array(
            -1 => Lang::get('general.choose_semester'),
            1 => 1,
            2 => 2,
            3 => 3,
            4 => 4,
            5 => 5,
            6 => 6);
    }

    public static function convertLevel($acc) {
        switch ($acc) {
            case self::bachelor :
                return Lang::get('general.bachelor');
                break;
            case self::master :
                return Lang::get('general.master');
                break;
        }
    }

    public static function convertgrade($acc) {

        switch ($acc) {
            case self::master :
                return Lang::get('general.msc');
                break;
            case self::phdcan :
                return Lang::get('general.phdcandidat');
                break;

            case self::dr :
                return Lang::get('general.dr');
                break;

            case self::akademik :
                return Lang::get('general.akademik');
                break;
        }
    }

    public static function convertTransfer($acc) {

        switch ($acc) {
            case self::transfer :
                return Lang::get('general.yes');
                break;
            case self::jotransfer:
                return Lang::get('general.no');
                break;
        }
    }

    public static function convertstatusi($statusi) {

        switch ($statusi) {
            case self::irregullt :
                return Lang::get('general.regular');
                break;
            case self::irregullt :
                return Lang::get('general.joirregullt');
                break;
        }
    }

    public static function convertdrejtimi($id) {
        $drejtimi = Drejtimet::where('idDrejtimet', '=', $id)->get();
        return $drejtimi[0]['Emri'];
    }

    public static function convertUID($id) {

        $user = Studenti::where('uid', '=', $id)->get();
        if ($user->count() < 1) {
            $user = Admin::where('uid', '=', $id)->get();
        }
        return $user[0]['emri'] ." " . $user[0]['mbiemri'];
    }

    public static function convertaccess($acc) {

        switch ($acc) {
            case self::student :
                return Lang::get('general.student');
                break;

            case self::puntor :
                return Lang::get('general.workers');
                break;

            case self::prof :
                return Lang::get('general.professor');
                break;

            case self::referent :
                return Lang::get('general.referent');
                break;

            case self::dekani :
                return Lang::get('general.dekani');
                break;

            case self::drejtori :
                return Lang::get('general.director');
                break;
            case self::admin :
                return Lang::get('general.admin_it');
                break;
        }
    }

    public static function convertday($day) {
        switch ($day) {
            case self::hene :
                return Lang::get('general.monday');
                break;

            case self::marte :
                return Lang::get('general.tuesday');
                break;

            case self::merkure :
                return Lang::get('general.wednesday');
                break;

            case self::enjete :
                return Lang::get('general.thursday');
                break;

            case self::premte :
                return Lang::get('general.friday');

vpasis/app/views/admin/students/addStudentForm.blade.php
@extends('admin.index') 

@section('body')
<!-- Modal -->
<div class="modal fade" id="registerStudent" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
@stop



@section('content')
    @yield('body')
@stop

vpasis/app/views/admin/students/list_students.blade.php
@extends('admin.index')

@section('notification')

<!-- Regjistrimi Departmentit -->
@if(null !== Session::get('message') && Session::get('message') == Enum::successful)
<div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ Session::get('reason') }}
</div>
@elseif(Session::get('message') == Enum::failed)
<div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ Lang::get('warn.error_undefined') }}
</div>

@endif
<!-- End Regjistrimi Departmentit -->
@stop



@section('listStaff')
<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading form-inline">{{ Lang::get('general.student_list') }} 

        <div class="form-group ">
            <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
            <div class="input-group ">
                <div class="input-group-addon input-sm">{{ Lang::get('general.subject') }}</div>
                {{ Form::select('drejtimi', $listDrejtimet,end($listDrejtimet),array('id'=>'drejtimi', 'class'=>'form-control input-sm')) }}
            </div>
            <script>
                $('#drejtimi').change(function () {

                    var drejtimi = $("#drejtimi").val();
                    if (drejtimi >= 1) {

                        window.location.href = "{{ action('StudentController@getList') }}/0/" + drejtimi;

                    }
                });
            </script>
        </div>
    </div>
    <!-- Table -->
    <table class="table table-responsive table-hover">
        <tr>
            <th>#</th>
            <th>{{ Lang::get('general.name')}} {{ Lang::get('general.surname')}}</th>
            <th>{{ Lang::get('general.email') }}</th>
            <th>{{ Lang::get('general.phone')}}</th>
            <th>{{ Lang::get('general.gender') }}</th>
            <th>{{ Lang::get('general.registred_date') }}</th>
            <th> 
                <a href="#" class="btn btn-sm btn-success">
                    <span class="fa fa-file-excel-o fa-lg"></span> 
                </a>
                <a href="{{ action('StudentController@getListPrintPdf',array($rows,$drejtimi)) }}" type="button" class="btn btn-sm btn-danger">
                    <span class="fa fa-file-pdf-o fa-lg"></span> 
                </a>
                <a href="{{ action('StudentController@getListPrintPdfDirect',array($rows,$drejtimi)) }}" id="printPlanProgrammin" class="btn btn-sm btn-default">
                    <span class="fa fa-print fa-lg"></span>  
                </a></th>
        </tr>
        @foreach($students as $value)
        <tr>
            <td>{{ $value['uid'] }}</td>
            <td class='text-info '> {{ $value['emri']." ".$value['mbiemri'] }}</td>
            <td>{{ $value['email'] }}</td>
            <td>{{ $value['telefoni']}}</td>
            <td><b>{{ substr(Enum::convertgjinia($value['gjinia']),0,1) }}</b></td>
            <td>{{ substr($value['created_at'],0,10) }}</td>
            <td>
                <!-- Split button -->
                <div class="btn-group">
                    <a  href='{{ action('StudentController@getProfile',array($value['uid']))}}' class="btn btn-sm btn-primary">{{ Lang::get('general.view_profile') }}</a>
                    <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href='{{ action('StudentController@postEdit',array($value['uid']))}}'> {{ Lang::get('general.change') }} </a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href='{{ action('StudentController@getDelete',array($value['uid']))}}'><span class="fa fa-trash-o fa-lg" ></span> {{ Lang::get('general.delete') }}</a></li>
                    </ul>
                </div>
            </td>
        </tr>
        @endforeach
        <tr>
            <td colspan="7">
                <ul class="pagination">
                    @for($i=0; $i<=$page;$i++)
                    <li @if($i == $selectedPage)
                         class="active" 
                         @endif><a href="{{ action('StudentController@getList',array($i * $limitList,$drejtimi)) }}">{{ $i+1 }}</a></li>
                    @endfor
                </ul>
            </td>
        </tr>
    </table>
</div>
@stop

@section('content')
<h2 class='text-capitalize '>{{ Lang::get('general.student_list') }}</h2>
<hr>
@yield('notification')
@yield('listStaff')
@stop

vpasis/app/views/admin/students/profile.blade.php
@extends('admin.index')

@section('notification')

<!-- Regjistrimi Departmentit -->
@if(null !== Session::get('message') && Session::get('message') == Enum::successful)
<div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ Session::get('reason') }}
</div>
@elseif(Session::get('message') == Enum::failed)
<div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ Lang::get('warn.error_undefined') }}
</div>

@endif
<!-- End Regjistrimi Departmentit -->
@stop


@section('profile')
<br><br>
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">{{ Lang::get('general.student_details') }}</div>
        <div class="panel-body">
            <div class='col-lg-3'>
                <div class='img-thumbnail '>
                    <img src="/smpsfl/doc/avatar/{{  $profile['avatar'] }}" class="img img-rounded  img-responsive">
                </div>
            </div>
            <div class='col-lg-6'>
                <br>
                <strong class='text-uppercase fa-lg' >{{ $profile['emri']." ( ".$profile['emri_prindit']." ".$profile['mbiemri_prindit']." ) " .$profile['mbiemri'] }}</strong>

                <br>
                <strong>{{ Lang::get('general.uid') }}:</strong> {{ $profile['uid'] }} 
                <br><b>{{ Lang::get('general.birthdate') }}:</b>{{ $profile['datalindjes'] }}
                <br><b>{{ Lang::get('general.subject') }}:</b> {{ Enum::convertdrejtimi($profile['drejtimi']) }}
                <br><b>{{ Lang::get('general.semester') }}:</b> {{ $profile['semestri'] }}
            </div>
            <div class="col-lg-3">
                <ul class="list-group">
                    <li class="list-group-item"> <strong>{{ Lang::get('general.contract_fee') }}: </strong><span class="label label-info" >{{ $profile['kontrata_pageses'] }} <span class="fa fa-euro"></span> </span> </li>
                    <li class="list-group-item"><strong>{{ Lang::get('general.installments') }}: </strong> {{ $profile['keste'] }}</li>
                    <li class="list-group-item "><strong>{{ Lang::get('general.installments_month') }}: </strong> <span class="label label-info" >{{ $profile['kontrata_pageses']/$profile['keste']  }} <span class="fa fa-euro"></span></span>  </li>
                </ul>
                <a class="btn btn-info" href="/smpsfl/doc/kontrata/student/{{ $profile['kontrata_dir'] }}"><span class="fa fa-print fa-lg"></span></a>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-6">
    <br>
    <div class="panel panel-default">
        <div class="panel-heading">{{ Lang::get('general.student_details') }}</div>
        <div class="panel-body">
            <ul class="list-group">
                <li class="list-group-item"> <strong>{{ Lang::get('general.location') }}: </strong>{{ $profile['vendbanimi'] }} - {{ $profile['adressa'] }}</li>
                <li class="list-group-item"><strong>{{ Lang::get('general.birthplace') }}: </strong> {{ $profile['vendlindja'] }}</li>
                <li class="list-group-item"><strong>{{ Lang::get('general.gender') }}: </strong> {{ Enum::convertGjinia($profile['gjinia']) }}</li>
                <li class="list-group-item"><strong>{{ Lang::get('general.phone') }}: </strong> {{ $profile['telefoni'] }}</li>
                <li class="list-group-item"><strong>{{ Lang::get('general.email') }}: </strong> {{ $profile['email'] }}</li>
                <li class="list-group-item"><strong>{{ Lang::get('general.idpersonal') }}: </strong> {{ $profile['nrpersonal'] }}</li>
            </ul>
        </div>
    </div>
</div>
<div class="col-lg-6">
    <br>
    <div class="panel panel-default">
        <div class="panel-heading">{{ Lang::get('general.education_details') }}</div>
        <div class="panel-body">
            <ul class="list-group">
                <li class="list-group-item"> <strong>{{ Lang::get('general.subject') }}: </strong>{{ Enum::convertdrejtimi($profile['drejtimi'])  }} </li>
                <li class="list-group-item"><strong>{{ Lang::get('general.level') }}: </strong> {{ Enum::convertLevel($profile['niveli']) }}</li>
                <li class="list-group-item"><strong>{{ Lang::get('general.status') }}: </strong> {{ Enum::convertStatusi($profile['statusi']) }}</li>
                <li class="list-group-item"><strong>{{ Lang::get('general.academic_year') }}: </strong> {{ $profile['viti_aka'] }}</li>
                <li class="list-group-item"><strong>{{ Lang::get('general.transfer') }}: </strong> {{ Enum::convertTransfer($profile['transfer']) }}</li>
                <li class="list-group-item"><strong>{{ Lang::get('general.qualification') }}: </strong> {{ $profile['kualifikimi'] }}</li>
            </ul>
        </div>
    </div>
</div>

@stop


@section('vijushmeria')
<br>

<div class="panel panel-default">
    <div class="panel-heading">{{ Lang::get('general.attendance') }}</div>
    <div class="panel-body">
        <table class='table table-responsive table-bordered'>
            <tr>
                <th>{{ Lang::get("general.course") }}</th>
                <th>{{ Lang::get("general.professor") }}</th>
                <th>{{ Lang::get("general.num_hour")}}</th>
            </tr>
            @foreach($vijushmeria as $value)
            <tr>
                <td>{{ $value['lenda'] }}</td>
                <td>{{ $value['prof'] }}</td>
                <td>{{ $value['numhour'] }}</td>
            </tr>
            @endforeach
        </table>

    </div>
</div>

@stop

@section('pagesat')
<br>
<div class="panel panel-default">
    <div class="panel-heading">

        {{ Lang::get('general.list_fee') }}

    </div>
    <div class="panel-body">
        <div class="col-lg-offset-11 col-lg-1">
            <a class="btn btn-info" href="{{ action('StudentController@getPrintListPagesat',array($profile['uid'])) }}">
                <span class="fa fa-print fa-lg"></span>
            </a>
        </div>
        <br>
        <br>
        <table class='table table-responsive table-bordered'>
            <tr>
                <th>#</th>
                <th>{{ Lang::get('general.bank_name') }}</th>
                <th>{{ Lang::get('general.description_fee') }}</th>
                <th>{{ Lang::get('general.feetype') }}</th>
                <th>{{ Lang::get('general.sum') }}</th>
                <th>{{ Lang::get('general.registred');$numFee=0 }}</th>
            </tr>

            @foreach($pagesat as $value)
            <tr>
                <td>{{ ++$numFee}}</td>
                <td>{{ $value['emri_bankes'] }}</td>
                <td>{{ $value['pershkrimi'] }}</td>
                <td>{{ Enum::convertLlojetPagesave($value['tipi']) }}</td>
                <td><span class="label label-info">{{ $value['shuma'];$shumaPaguar = $shumaPaguar + $value['shuma'] }} <span class="fa fa-euro"></span> </span></td>
                <td>{{ $value['created_at'] }}</td>
            </tr>
            @endforeach
            <tr>
                <td colspan="4" class="text-right bold">{{ Lang::get('general.total_sum') }}</td>
                <td><span class="label label-primary">{{ $shumaPaguar }} <span class="text-center fa fa-lg fa-euro"></span> </span></td>
            </tr>
        </table>

    </div>
</div>
@stop

@section('notimet')

<br>
<div class="panel panel-default">
    <div class="panel-heading">

        {{ Lang::get('general.exams') }}

    </div>
    <div class="panel-body">

        <table class='table table-responsive table-bordered'>
            <tr>
                <th>#</th>
                <th>{{ Lang::get('general.course') }}</th>
                <th>{{ Lang::get('general.grade') }}</th>
                <th>{{ Lang::get('general.lecturer') }}</th>
                <th>{{ Lang::get('general.date') }}</th>
                @if($settings['provim_active'] == Enum::yes)
                <th>{{ Lang::get('general.refuse')}}</th>
                <th>{{ Lang::get('general.apply')}}</th>
                @endif
                <th>{{ Lang::get('general.attendance')}}</th>
            </tr>
            @foreach($notimet as $value)
            <tr>
                <td> </td>
                <td>{{ $value['lenda'] }}</td>
                <td>{{ $value['nota'] }}</td>
                <td>{{ $value['prof'] }}</td>
                <td>{{ $value['data'] }}</td>
            </tr>
            @endforeach
        </table>
    </div>
</div>

@stop



@section('content')


<h2 class='text-capitalize '>{{ $profile['emri']." ".$profile['mbiemri'] }}</h2>
<hr>
@yield('notification')

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">{{ Lang::get('general.student_profile') }}</a></li>
    <li role="presentation"><a href="#vijushmeria" aria-controls="vijushmeria" role="tab" data-toggle="tab">{{ Lang::get('general.attendance') }}</a></li>
    <li role="presentation"><a href="#notimet" aria-controls="notimet" role="tab" data-toggle="tab">{{ Lang::get('general.exams') }}</a></li>
    <li role="presentation"><a href="#pagesat" aria-controls="pagesat" role="tab" data-toggle="tab">{{ Lang::get('general.fee') }}</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="profile">@yield('profile')</div>
    <div role="tabpanel" class="tab-pane" id="vijushmeria">@yield('vijushmeria')</div>
    <div role="tabpanel" class="tab-pane" id="notimet">@yield('notimet')</div>
    <div role="tabpanel" class="tab-pane" id="pagesat">@yield('pagesat')<div>
        </div>

    </div>

    @stop